[text-v14]
keyphrases = ["istextbased is not a function"]
content = """
Use `v14.11.0` or newer of discord.js: `npm i discord.js@latest` *(more: https://discord.com/channels/222078108977594368/1091094485754187907/1091094485754187907 )*
"""
mention = true
reply = true

[text-v13]
keyphrases = ["istext is not a function"]
content = """
Use `v13.14.0` or newer of discord.js: `npm i discord.js@v13-lts` *(more: https://discord.com/channels/222078108977594368/1091094485754187907/1091094485754187907 )*
"""
mention = true
reply = true
